on:
  push
  
jobs:
    update:
      runs-on: ubuntu-latest
      
      steps:
        - name: Setup Python
          uses: actions/setup-python@v3 
          with:
            python-version: 3.8
            
        - name: Install Databricks CLI
          uses: databricks/setup-cli@main

        - name: Remote update Prod Repo 
          env:
            DATABRICKS_HOST: $
            DATABRICKS_TOKEN: $
          run: |
            databricks repos update "/Workspace/Repos/aliaksandra_arlouskaya1@epam.com/myrepository"
